### ISSUE TITLE
Reopen itch.io pages?

### ISSUE THREAD

**Issue by jpenguin** [jorio/OttoMatic#14]
Just curious if your going to open up the itch.io pages for these games back up?

**Comment by jorio** [comment]
Yes! I just wanted to finish a slew of bugfixes across all ports first, so the page opens back up with fresh versions.

**Comment by jpenguin** [comment]
Great page, lovre the background choice.

Other classic wallpappers are available https://www.macintoshrepository.org/10646-macos-desktop-patterns-pictures
