### ISSUE TITLE
Any way to change Windowed/Fullscreen resolutions via a menu option?

### ISSUE THREAD

**Issue by eisnerguy1** [jorio/OttoMatic#17]
I was wondering if there was any way to change the resolution of the game via a menu option? I know that there is the "--fullscreen-resolution WIDTH HEIGH" command line option but, there's no option to change the resolution while in Windowed mode. Ideally, I'd love an option to have the game's resolution as 1280x960/2x scaled. Or, if that can't be done, maybe include a command line option for "--windowed-resolution WIDTH HEIGH" and also include 1280x960 as a valid option?

My main issue is that the UI just stretches and is pretty spaced apart while in Windowed or Fullscreen mode.
<img width="1280" alt="Ottomatic" src="https://user-images.githubusercontent.com/3295271/170895260-e859213f-09e4-4bf1-abbb-2d0d761c307d.png">

Thanks!

**Comment by eisnerguy1** [comment]
Awesome! Thank you! That's my only tiny issue with the game. This, and the other updated Pangea games run great on my 2015 MacBook Pro.

**Comment by jorio** [comment]
[https://github.com/jorio/OttoMatic/releases/tag/4.0.1](Otto Matic) adds settings for infobar scaling and centering. When centering is on, UI elements are placed as they would be on a 4:3 screen. This is similar to the infobar centering option that I added to Nanosaur 2. I hope that helps!
