### ISSUE TITLE
MIssing .ddl files? 

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#19]
When I try to zip up [a compiled modification](https://ftl.deekshith.eu.org/385739/OttoMaticUncapped.zip?hash=AgADwg) of the game, it seems to report an error that there are many missing .ddl files, such as [this one.](https://www.dll-files.com/download/a075828073369628bcca8a80fa225744/vcruntime140.dll.html?c=VTVtMEdBMlBZV2d3SFRndUFHYlRCUT09) How can I make these mods portable so they are playable?[ The precompiled package](https://github.com/jorio/ottomatic/releases) on here seems to not have any .ddl's in it. How can It be made portable and launchable when sent?

**Comment by jorio** [comment]
Your second link doesn't seem to point to the right address, so I can't see what DLL files the game is complaining about. Can you please list some of the missing files?

**Comment by foote-darrell** [comment]
Sorry, I updated it now. There were many of them.

**Comment by jorio** [comment]
Ah, yes. Shipping these DLLs is something I've fixed in 2 of the other games, but I haven't had time to do it on Otto Matic yet.

In the meantime, installing the "Visual C++ redistributable" from Microsoft will most likely fix this issue: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by jorio** [comment]
Fixed in Otto Matic 4.0.1
