### ISSUE TITLE
Modify the game for the Steam Deck?

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#22]
The Steam Deck has controller input. The remastered version of _Otto Matic_ is integrated with controller support that works greatly. The Steam Deck however has lots of shoulder buttons and grip buttons that aren't used for anything in the game. How can the game be modified to take the input of those buttons for actions like the starting on any level dialog, or the full health cheat? How would you be able to find out what input codes those extra buttons have?
![Screenshot from 2022-08-03 23-14-41](https://user-images.githubusercontent.com/70550621/182778408-863494f0-a12f-4b21-80fa-7dbc8d08dd15.png)

**Comment by foote-darrell** [comment]
In particular, would there be a way to add the B-R-I cheat function on the gamepad configation? Thanks Mr. Dinosaur man.

**Comment by jorio** [comment]
@foote-darrell Regarding your first comment, do you mean the game doesn't recognize some of the Steam Deck's buttons when you try to assign a new button to an action?

**Comment by foote-darrell** [comment]
No, I mean to assign the B-R-I cheat to a gamepad button. To add this function to the gamepad interface.

**Comment by philhzss** [comment]
Hey @jorio  or @foote-darrell , how did you get it to show "Steam virtual gamepad"? For me, it just says "no controller detected", and I have to use a Steam Input preset that just simulates keyboard + mouse, I can't use any gamepad presets.
Can you help me?
Thank you!

**Comment by jorio** [comment]
@philhzss I don't have a Steam Deck, but you can try this:

- Try replacing Data/System/gamecontrollerdb.txt with [a more recent version of that file](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)
- Try compiling the game against a recent version of SDL. You can use `python3 build.py` which will make an AppImage that uses with SDL 2.0.22.

**Comment by philhzss** [comment]
@jorio Thank you for that, I tried the first option but I'm relatively new to the Steam Deck and to Linux and really had trouble finding the folders of Otto Matic's install... I used the "Discover Store" that comes with the deck, looks like it installs Otto Matic with Flatpak/flathub or something. I'm not sure. Anyway I think I found the file, replaced it but it didn't change anything. I might have done it wrong though haha

I will take look at the 2nd option soon, thanks!

**Comment by jorio** [comment]
@philhzss In case you're still interested, the flatpak apparently had broken gamepad support for all systems (see #24). I fixed that, so chances are it works on the Steam Deck now.

**Comment by philhzss** [comment]
@jorio  
Just tried it, it works perfectly!!! Merci!!!
A tip to anyone else having issues; I still had my Steam Deck controller config for Otto Matic set to emulate a keyboard and mouse, and it wasn't detecting the gamepad when I launched the new version... I had to select a "Gamepad" controller config, close Otto Matic, re-open it, and then everything worked!
This shouldn't be an issue if you just downloaded Otto Matic of course, I had manually configured mine to emulate keyboard + mouse since the gamepad wasn't working initially, but this is no longer required.

I think you can close the issue

**Comment by jorio** [comment]
De rien ;)

As for the original inquiry in this issue, the level select screen is still accessible with a controller by pressing “Start” while holding down “Back” (I believe that would be pressing Menu while holding down View on the Steam Deck).

**Comment by foote-darrell** [comment]
But how can you set the B+R+I cheat to a gamepad button?

**Comment by philhzss** [comment]
@foote-darrell 
Couldn't you just choose any gamepad button that is not used, and then in the Steam input config go to add those 3 keyboard commands to the button?

**Comment by foote-darrell** [comment]
That would require the gamepad mapped as a keyboard. This is for an Xbox controller on desktop though. How can the full health and inventory cheat be mapped to a gamepad button?

**Comment by philhzss** [comment]
> That would require the gamepad mapped as a keyboard. This is for an Xbox controller on desktop though. How can the full health and inventory cheat be mapped to a gamepad button?

Oh ok I thought you were on the Steam Deck. Ummm as far as I know you can use the same steam input stuff on desktop than on the deck though?

So, I haven't played Otto Matic for a whole but I'm sure theres at least 1 button on the gamepad that you're not using? Otto Matic doesn't have that many controls. Just for that specific button, you can set it to emulate the keyboard in steam input (just for that button). You can still have the rest of the gamepad as a regular gamepad
