### ISSUE TITLE
Flatpak version missing controller support

### ISSUE THREAD

**Issue by icup321** [jorio/OttoMatic#24]
The Flatpak version of Otto Matic does not seem to detect my Xbox 360 controller, but the appimage version works as intended. Did not check other games, just this one.

**Comment by jorio** [comment]
Let me know if this build works for you:

```
flatpak install --user https://dl.flathub.org/build-repo/4439/io.jor.ottomatic.flatpakref
```

(For details, see https://github.com/flathub/io.jor.ottomatic/pull/5)

**Comment by icup321** [comment]
Yes, it's working now.

**Comment by jorio** [comment]
Great! The official flatpak will be updated tonight.
The flatpaks for the other Pangea games are also affected, I'll update them when I have time.
Thanks for raising this issue!
