### ISSUE TITLE
Building the Otto 4.0.1 update on a new Ubuntu install

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#25]
My computer had unfortunately failed, so had to completely reset it completely. I had followed the build instructions and downloaded all the prerequisites. It says now that configuing is incomplete, errors occurred. CMake is installed, but it says that it is the wrong tool? For the whole session, [here is the entire output.](https://archive.org/details/building-otto)
```
darrell@darrell-Lenovo-H430:~/OttoMatic$ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/darrell/OttoMatic/build/CMakeFiles/CMakeOutput.log".

```

**Comment by jorio** [comment]
sudo apt install build-essential

**Comment by foote-darrell** [comment]
That fixed it right away. Is that included in the python script, or is that also a prerequisite to the script?

**Comment by jorio** [comment]
Glad you got it fixed. It’s implied by “install any C++20 compiler” in the build instructions. Different Linux distributions have different ways of accomplishing that; on Ubuntu, that’s “apt install build-essential”. This package provides essential tools to compile C/C++ on Ubuntu.
