### ISSUE TITLE
Info Bar Glow & Supernova Spark

### ISSUE THREAD

**Issue by RossDarker** [jorio/OttoMatic#27]
In earlier versions of the game, the Supernova in the info bar had a moving spark between the antennae.
This spark seems to have gone missing at some point, as it is not in the current version of the game here, nor the latest iOS Pangea release.

I haven't seen this mentioned anywhere, but I'm quite fond of the spark, so if it can be restored to this version on GitHub, that would be great.

Version 2.0.1:
![](https://i.imgur.com/2EJkz2O.png)

Version 4.0.1:
![](https://i.imgur.com/fEoXWfk.png)

The spark can be seen moving here:
https://www.youtube.com/watch?v=n0A5z3xBuRc&t=114s

Also, thanks for the updated version!

**Comment by RossDarker** [comment]
Looking into this, it appears that the glow around each weapon in the infobar is not correct in v4.0.1 (look at the fist for example, quite noticeable there), but this is correct in 4.0.0.
This seems to have something to do with the spark on the supernova as well, as it is present in 4.0.0.

Can't quite figure out exactly what the problem is, but I can see some changes regarding the glow in the code across versions.

**Comment by jorio** [comment]
Ah, yes, good catch. This icon is weird: the spark exists in the color channels, but the alpha channel masks it out. And yet, the original game threw away the alpha channel for all glow images; this part got lost in translation in 4.0.1. I'll fix this in the coming days. Thanks!

**Comment by jorio** [comment]
Fixed, thanks! I don't think this fix alone warrants a new release today, but I'll ship it in the next maintenance release, whenever that happens.

In the meantime, you can simply copy the **Data/sprites/infobar** folder from this git repo to your existing install of version 4.0.1, and the spark and soft glows should be back.
