### ISSUE TITLE
Saucer abductions from behind a gate

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#28]
Thus update claimed that the saucers won't attempt to abduct the people if there is a closed gate between them. However it just happened in _Level 4: Planet Knarr_ after the first teleported, clearly right behind the gate. How ought this be solved?
![Screenshot from 2023-11-12 20-32-23](https://github.com/jorio/OttoMatic/assets/70550621/e5d3b8ad-e29d-4f89-8d05-591897faf5bf)
![Screenshot from 2023-11-12 20-32-29](https://github.com/jorio/OttoMatic/assets/70550621/fc38060e-3d51-4a6b-a358-dea3fa4533eb)

**Comment by jorio** [comment]
The saucer is summoned if a ray can be cast between Otto and the human without crossing any fences or gates.

In this particular case, the slope between Otto and the human is steep enough that the raycast goes straight through the slope without hitting the gate.

I'll sink the gate's collision box deeper into the ground to compensate for the slope.

**Comment by jorio** [comment]
Fixed, feel free to reopen if that didn't work
