### ISSUE TITLE
Cheat codes and unlimited weapons inventory

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#3]
In addition to the full rings of health, jump-jet, rocket fuel, and lives, I saw that the B-R-I cheat code now gives a full inventory of 99 ray gun ammunition and supernovas.

Do to the advent of this game being open-source, what would it take to modify the cheat code to give full ammunition of _all_ weapons and items, including the growth potions?

In the mobile version, weapon ammunition did carry over between levels, so it was possible to use weapons that weren't supplied on the levels. Some weapons, such as the freeze gun, had no use in some of the levels, but it was still useful to have all the ammunition. Why ought the cheat code only give ray-guns and supernovas?

**Comment by orazioedoardo** [comment]
> Do to the advent of this game being open-source, what would it take to modify the cheat code to give full ammunition of all weapons and items, including the growth potions?

If you know some of C programming, you can easily give you infinite ammo of everything, change the walk speed, give unlimited health, walk through fences.

Personally, I use the `grep` utility on Linux/Unix to look for interesting stuff like `weapon`, `collision`, `health`, `gravity`, `ammo` and then inspect the source files, it's very educational too.

> Why ought the cheat code only give ray-guns and supernovas?

[Here's an hint](https://github.com/jorio/OttoMatic/blob/c047bea2de28cf1640c248140c146d453cfc895c/src/Player/Player_Robot.c#L2816-L2831).

**Comment by jpenguin** [comment]
[Here are the weapon names to add to the cheat](https://github.com/jorio/OttoMatic/blob/48becd8e8edc51c4e55b5b79b4019b859d762dd2/src/Headers/globals.h#L170)

**Comment by jorio** [comment]
B+R+I gives all weapons in Otto 4.0.1.
