### ISSUE TITLE
Port the game to Android or Nintendo Switch?

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#30]
There was a mobile version of _Otto Matic_ on the iPhone [that is still being sold.](https://apps.apple.com/us/app/otto-matic/id306811786) Does the scope of this remaster include mobile devices?

**Comment by jorio** [comment]
There are no plans to port the game to additional platforms. Your best options for playing the game on the go are the Steam Deck or indeed Pangea's iOS version.
