### ISSUE TITLE
Create a random level option in the level menu?

### ISSUE THREAD

**Issue by foote-darrell** [jorio/OttoMatic#8]
I am new to this stuff, but what would it take to make a _"Random"_ option in the level cheat menu? Just make it set `LEVEL_NUM` to a random integer between 1 and 10? It ought to be a simple and trivial thing to make.

**Comment by foote-darrell** [comment]
I got to know how to do this.

**Comment by foote-darrell** [comment]
I still need to find out how

**Comment by foote-darrell** [comment]
[Seemingly in the LevelCheat.c file,](https://github.com/jorio/OttoMatic/blob/master/src/Screens/LevelCheat.c) there seem to be macros that define the names of the strings. Where are the macros from? The only search results that return are from [this list.](https://github.com/jorio/OttoMatic/blob/48becd8e8edc51c4e55b5b79b4019b859d762dd2/src/Headers/localization.h) The strings seem to be [in here.](https://github.com/jorio/OttoMatic/blob/c047bea2de28cf1640c248140c146d453cfc895c/Data/System/strings.tsv) Where are the actual macros defined?

Is there a way to trype in a string literal directly the .c file? Does the project have any way to create a random integer for levels 1 thorugh 10? There seem to be many results of RandomFloat, but none for an integer.

**Comment by foote-darrell** [comment]
@jorio to date, still no answer.

**Comment by jorio** [comment]
Merry Christmas:

```c
int DoLevelCheatDialog(void (*backgroundDrawRoutine)(void))
{
	static const MenuItem kLevelCheatMenu[] =
	{
		{.type=kMenuItem_Title,		.text=STR_LEVEL_CHEAT},
		{.type=kMenuItem_Spacer},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_1,		.pick=0},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_2,		.pick=1},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_3,		.pick=2},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_4,		.pick=3},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_5,		.pick=4},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_6,		.pick=5},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_7,		.pick=6},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_8,		.pick=7},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_9,		.pick=8},
		{.type=kMenuItem_Pick,		.text=STR_LEVEL_10,		.pick=9},
		{.type=kMenuItem_Pick,		.rawText="* RANDOM *",	.pick=10},
		{.type=kMenuItem_END_SENTINEL},
	};

	int pick = StartMenu(kLevelCheatMenu, nil, nil, backgroundDrawRoutine);

	if (pick == 10)
	{
		pick = MyRandomLong() % 10;   // random number in range [0...9]
	}

	return pick;
}
```

**Comment by foote-darrell** [comment]
Why not the Random level option in the 4.0.1 update? This a feature is a great improvement.
